#!/usr/bin/env python3
"""
Quick Start Setup Script for Polymarket Scanner
Helps configure the scanner interactively
"""

import os
import sys


def print_header():
    print("\n" + "="*70)
    print("🔍 POLYMARKET INSIDER TRADING SCANNER - QUICK SETUP")
    print("="*70 + "\n")


def check_dependencies():
    """Check if required packages are installed"""
    print("📦 Checking dependencies...")
    
    missing = []
    
    try:
        import requests
    except ImportError:
        missing.append("requests")
    
    try:
        import websockets
    except ImportError:
        missing.append("websockets")
    
    if missing:
        print(f"\n❌ Missing dependencies: {', '.join(missing)}")
        print("\nInstall them with:")
        print(f"  pip install {' '.join(missing)}")
        return False
    
    print("✅ All dependencies installed\n")
    return True


def get_telegram_credentials():
    """Get Telegram bot token and chat ID"""
    print("📱 TELEGRAM SETUP")
    print("-" * 70)
    print("\nTo receive alerts via Telegram, you need:")
    print("1. A bot token from @BotFather")
    print("2. Your chat ID from @userinfobot")
    print("\nLeave blank to skip Telegram (alerts will only be logged)\n")
    
    bot_token = input("Enter your Telegram Bot Token: ").strip()
    
    if not bot_token:
        print("⚠️  Telegram notifications will be disabled")
        return None, None
    
    chat_id = input("Enter your Telegram Chat ID: ").strip()
    
    if not chat_id:
        print("⚠️  Telegram notifications will be disabled")
        return None, None
    
    print("✅ Telegram configured\n")
    return bot_token, chat_id


def configure_thresholds():
    """Configure alert thresholds"""
    print("\n⚙️  ALERT THRESHOLDS")
    print("-" * 70)
    print("\nCurrent defaults:")
    print("  Large bet: $5,000")
    print("  Very large bet: $10,000")
    print("  Huge bet: $50,000")
    
    use_defaults = input("\nUse default thresholds? (Y/n): ").strip().lower()
    
    if use_defaults != 'n':
        return 5000, 10000, 50000
    
    try:
        large = int(input("Large bet threshold ($): ").strip() or "5000")
        very_large = int(input("Very large bet threshold ($): ").strip() or "10000")
        huge = int(input("Huge bet threshold ($): ").strip() or "50000")
        return large, very_large, huge
    except ValueError:
        print("⚠️  Invalid input, using defaults")
        return 5000, 10000, 50000


def create_config_file(bot_token, chat_id, large, very_large, huge):
    """Create config.py with user settings"""
    
    config_content = f'''"""
Configuration file for Polymarket Scanner
Auto-generated by quick_start.py
"""

import os

# ============================================================================
# TELEGRAM CONFIGURATION
# ============================================================================

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "{bot_token or 'YOUR_BOT_TOKEN_HERE'}")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "{chat_id or 'YOUR_CHAT_ID_HERE'}")
ENABLE_TELEGRAM = {str(bool(bot_token and chat_id))}

# ============================================================================
# ALERT THRESHOLDS
# ============================================================================

LARGE_BET_THRESHOLD = {large}
VERY_LARGE_BET_THRESHOLD = {very_large}
HUGE_BET_THRESHOLD = {huge}

NEW_WALLET_HOURS = 168
VERY_NEW_WALLET_HOURS = 24

HIGH_WIN_RATE_THRESHOLD = 0.65
LOW_TRADE_COUNT_THRESHOLD = 10
MIN_VOLUME_FOR_ANALYSIS = 1000

SIGNIFICANT_ODDS_MOVE = 0.10
RAPID_ODDS_TIME_WINDOW = 3600

# ============================================================================
# SCANNING CONFIGURATION
# ============================================================================

TRADE_POLL_INTERVAL = 30
MARKET_REFRESH_INTERVAL = 300
WALLET_CACHE_TTL = 300

MAX_MARKETS_TO_TRACK = 100
ONLY_HIGH_LIQUIDITY = False
MIN_MARKET_LIQUIDITY = 10000

CATEGORIES_TO_MONITOR = []
CATEGORIES_TO_EXCLUDE = []

# ============================================================================
# HISTORICAL ANALYSIS
# ============================================================================

ANALYZE_HISTORY_ON_START = True
HISTORICAL_DAYS = 7
MIN_TRADES_FOR_PERFORMER = 10
TOP_PERFORMERS_TO_SHOW = 10

# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================

DB_PATH = "polymarket_scanner.db"

KEEP_TRADES_DAYS = 90
KEEP_ALERTS_DAYS = 30
KEEP_PRICES_DAYS = 7

# ============================================================================
# API CONFIGURATION
# ============================================================================

GAMMA_API = "https://gamma-api.polymarket.com"
DATA_API = "https://data-api.polymarket.com"
CLOB_API = "https://clob.polymarket.com"

MAX_REQUESTS_PER_MINUTE = 100
REQUEST_DELAY = 0.5

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================

LOG_LEVEL = "INFO"
LOG_FILE = "scanner.log"
LOG_FORMAT = "%(asctime)s - %(levelname)s - %(message)s"

# ============================================================================
# ADVANCED FEATURES
# ============================================================================

ALERT_NEW_WALLET_LARGE_BET = True
ALERT_SINGLE_MARKET_FOCUS = True
ALERT_HIGH_WINRATE_LOW_TRADES = True
ALERT_RAPID_ODDS_MOVEMENT = True
ALERT_WHALE_ACTIVITY = True

MIN_ALERT_SEVERITY = "MEDIUM"

DAILY_SUMMARY_HOUR = None

WATCHED_WALLETS = []
IGNORED_WALLETS = []

# ============================================================================
# VALIDATION
# ============================================================================

def validate_config():
    """Validate configuration values"""
    errors = []
    
    if ENABLE_TELEGRAM:
        if TELEGRAM_BOT_TOKEN == "YOUR_BOT_TOKEN_HERE":
            errors.append("TELEGRAM_BOT_TOKEN not configured")
        if TELEGRAM_CHAT_ID == "YOUR_CHAT_ID_HERE":
            errors.append("TELEGRAM_CHAT_ID not configured")
    
    if LARGE_BET_THRESHOLD >= VERY_LARGE_BET_THRESHOLD:
        errors.append("LARGE_BET_THRESHOLD must be less than VERY_LARGE_BET_THRESHOLD")
    
    if VERY_LARGE_BET_THRESHOLD >= HUGE_BET_THRESHOLD:
        errors.append("VERY_LARGE_BET_THRESHOLD must be less than HUGE_BET_THRESHOLD")
    
    if errors:
        print("\\n⚠️  Configuration Errors:")
        for error in errors:
            print(f"  - {{error}}")
        return False
    
    return True
'''
    
    with open("config.py", "w") as f:
        f.write(config_content)
    
    print("\n✅ Configuration file created: config.py\n")


def show_next_steps():
    """Show what to do next"""
    print("\n" + "="*70)
    print("🎉 SETUP COMPLETE!")
    print("="*70 + "\n")
    
    print("Next steps:")
    print("\n1. Start the scanner:")
    print("   python polymarket_scanner.py")
    
    print("\n2. View recent alerts:")
    print("   python alert_viewer.py list 24")
    
    print("\n3. Analyze a specific wallet:")
    print("   python wallet_analyzer.py <wallet_address>")
    
    print("\n4. Customize settings:")
    print("   Edit config.py to adjust thresholds and behavior")
    
    print("\nFor help and documentation, see README.md")
    print("\n" + "="*70 + "\n")


def main():
    """Main setup flow"""
    print_header()
    
    # Check dependencies
    if not check_dependencies():
        sys.exit(1)
    
    # Get Telegram credentials
    bot_token, chat_id = get_telegram_credentials()
    
    # Configure thresholds
    large, very_large, huge = configure_thresholds()
    
    # Create config file
    print("\n📝 Creating configuration file...")
    create_config_file(bot_token, chat_id, large, very_large, huge)
    
    # Show next steps
    show_next_steps()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Setup error: {e}")
        sys.exit(1)
